# Mehrere Includes als Liste
- include: package:very_good_analysis/analysis_options.yaml

- analyzer:
    errors:
      lines_longer_than_80_chars: ignore
    exclude:
      - test/data/**
      - lib/generated/**
    
- linter:
    rules:
      # Deaktiviere z.B. unnötige Regeln
      always_put_required_named_parameters_first: false
      avoid_positional_boolean_parameters: false